"""AI 披露扫描（check_ai_disclosure）回归测试。

覆盖：7 种披露模式各命中 1 例；反例（不应误报的正常句子）。
这是发布前硬门禁，任何回归都意味着 AI 身份可能泄漏到公众号。
"""

import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from publish_history import check_ai_disclosure


class AIDisclosureHitTests(unittest.TestCase):
    """正例：以下句子必须命中并返回结果（raise_on_hit=False 时）。"""

    def _hits(self, text):
        return check_ai_disclosure(text, raise_on_hit=False)

    def test_pattern_本文由_ai_协助撰写(self):
        self.assertTrue(self._hits("本文由 AI 协助撰写，仅供参考。"))

    def test_pattern_人工智能辅助生成(self):
        self.assertTrue(self._hits("以上内容由人工智能辅助生成。"))

    def test_pattern_借助_hermes(self):
        self.assertTrue(self._hits("本文部分内容借助 Hermes 生成。"))

    def test_pattern_利益相关(self):
        self.assertTrue(self._hits("利益相关：本文作者持有相关股票。"))

    def test_pattern_本公众号由_ai(self):
        self.assertTrue(self._hits("本公众号内容由大模型生成。"))

    def test_pattern_以上内容由_ai(self):
        self.assertTrue(self._hits("以上内容由 AI 总结。"))

    def test_pattern_english_disclosure(self):
        self.assertTrue(self._hits("This article was generated by AI."))


class AIDisclosureNoFalsePositiveTests(unittest.TestCase):
    """反例：以下正常句子不应命中（防误报）。"""

    def _hits(self, text):
        return check_ai_disclosure(text, raise_on_hit=False)

    def test_openai_company_name(self):
        # 提到公司名 OpenAI，但没有"由AI撰写"句式
        self.assertEqual(self._hits("这家公司叫 OpenAI，估值很高。"), [])

    def test_gpt_as_example(self):
        # 用 GPT 举例，不是声明本文由AI写
        self.assertEqual(self._hits("比如你可以用 GPT 写个脚本。"), [])

    def test_ai_field_normal_sentence(self):
        # 谈论 AI 领域，但不是披露
        self.assertEqual(self._hits("人工智能领域最近有很多进展。"), [])

    def test_normal_finance_sentence(self):
        # 正常财经句，不应命中
        self.assertEqual(self._hits("利率变化影响普通人的房贷成本。"), [])


class AIDisclosureRaiseTests(unittest.TestCase):
    """raise_on_hit=True（默认）命中即 SystemExit(2)。"""

    def test_raises_on_hit(self):
        with self.assertRaises(SystemExit) as ctx:
            check_ai_disclosure("本文由 AI 协助撰写。", raise_on_hit=True)
        self.assertEqual(ctx.exception.code, 2)

    def test_no_raise_on_clean(self):
        # 干净文本不应抛异常
        check_ai_disclosure("这是一篇正常的文章。", raise_on_hit=True)


if __name__ == "__main__":
    unittest.main()
